#!/bin/sh

# Ensure that the user has provided a URL
if [ "$#" -ne 1 ]
then
  echo "Usage: mdl <url>"
  exit
fi

# Ensure that the user has installed the required dependencies
if ! command -v yt-dlp > /dev/null 2>&1
then
  echo "yt-dlp could not be found"
  exit
fi

# Download the playlist
yt-dlp \
  --extract-audio \
  --format "ba[ext=m4a]" \
  --parse-metadata "playlist_index:%(track_number)s" \
  --add-metadata \
  --embed-thumbnail \
  --restrict-filenames \
  --output "%(title)s.%(ext)s" \
  --ppa 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="'"'"'if(gt(ih,iw),iw,ih)'"':'"'if(gt(iw,ih),ih,iw)'"'"'"' \
  "$1"

# Rename the files
for file in *.m4a
do
  name=$(echo "$file" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
  if [ "$name" != "$file" ]
  then
    mv "$file" "$name"
  fi
done
