#!/bin/sh

# Ensure that the user has provided a URL
if [ "$#" -ne 1 ]
then
    echo "Usage: mdl <url>"
    exit
fi


# Ensure that the user has installed the required dependencies
if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
    exit
fi

# Ensure that the user has installed the required dependencies
if ! command -v file-rename &> /dev/null
then
    echo "file-rename could not be found"
    exit
fi

# Download the playlist
yt-dlp \
  --extract-audio \
  --format "ba[ext=m4a]" \
  --parse-metadata "playlist_index:%(track_number)s" \
  --add-metadata \
  --embed-thumbnail \
  --restrict-filenames \
  --output "%(title)s.%(ext)s" \
  --ppa 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="'"'"'if(gt(ih,iw),iw,ih)'"':'"'if(gt(iw,ih),ih,iw)'"'"'"' \
  "$1"

# Rename the files
# Currently only supported on openSUSE
file-rename 'y/A-Z/a-z/' *.m4a
file-rename 'y/_/-/' *.m4a
